### ISSUE TITLE
Unable to get C++ snippets file to load in WSL 

### ISSUE THREAD

**Issue by TryerGit** [draivin/hsnips#152]
Hello,

On creating a simple `cpp.hsnips` file:

```
snippet eq "equals" iA
= 
endsnippet

```
and placing it in `C:\users\TryerGit\AppData\Roaming\Code\User\hsnips` folder 

and providing the following settings:

"hsnips.hsnipsPath": "%APPDATA%\\Code\\User\\hsnips"  in user `settings.json` that resides in `C:\Users\TryerGit\AppData\Roaming\Code\User`

"hsnips.hsnipsPath": "/mnt/c/users/TryerGit/AppData/Roaming/Code/User/hsnips/" in Remote [WSL:Ubuntu-20.04] `settings.json` which resides in `\\wsl$\Ubuntu-20.04\home\TryerGit\.vscode-server\data\Machine`

the snippet file still does not seem to be loaded. 

The following image is obtained which seems to indicate many uncaught errors between the local installed version and the WSL installed version.  The local installed version is greyed out but the WSL version is active. 

![hsnips](https://user-images.githubusercontent.com/70434658/214007369-b4ab89cd-dfe0-447c-8946-133243d64532.jpg)

Could you please help fix this issue?

Thanks.

**Comment by TryerGit** [comment]
Here is the log file in case this can help:

```
[2023-01-23 16:37:44.956] [exthost] [info] eager extensions activated
[2023-01-23 16:37:50.904] [exthost] [error] [draivin.hsnips] provider FAILED
[2023-01-23 16:37:50.905] [exthost] [error] TypeError: Cannot read property 'scopes' of null
	at Object.getCompletions (/home/TryerGit/.vscode-server/extensions/draivin.hsnips-0.2.8/out/completion.js:58:56)
	at Object.provideCompletionItems (/home/TryerGit/.vscode-server/extensions/draivin.hsnips-0.2.8/out/extension.js:160:44)
	at $.provideCompletionItems (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:176938)
	at /home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:197582
	at xe._withAdapter (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:187656)
	at xe.$provideCompletionItems (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:197558)
	at i._doInvokeHandler (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:98:13543)
	at i._invokeHandler (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:98:13227)
	at i._receiveRequest (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:98:11838)
	at i._receiveOneMessage (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:98:10567)
	at /home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:98:8663
	at c.fire (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at l.fire (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:15781)
	at /home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:113:30187
	at c.fire (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at l.fire (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:15781)
	at r._receiveMessage (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:21051)
	at /home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:17929
	at c.fire (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at v.acceptChunk (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:13142)
	at /home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:74:12490
	at c.fire (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at E._acceptChunk (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:113:19362)
	at /home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:113:15775
	at Socket.w (/home/TryerGit/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:113:13350)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```
