### ISSUE TITLE
Can't use dynamic imports in code interpolation.

### ISSUE THREAD

**Issue by itswin** [draivin/hsnips#30]
Context: I'm trying to get math expression evaluation working through snippets using the mathjs library (Particularly the evaluate function from mathjs).

Here's the snippet I'm using to test. I've verified the JS works on my machine.
```
snippet import "import test"
``
function load() {
  import('mathjs')
  .then(module => {
    console.log("Successful load");
    console.log(module.default.evaluate("sqrt(3^2+4^2)"));
  })
}

load();
``
endsnippet
```

I get the error

```
rejected promise not handled within 1 second: Error: Not supported
extensionHostProcess.js:1048
stack trace: Error: Not supported
	at load (eval at parse (c:\Users\Win33\Documents\Programming\hsnips\out\parser.js:115:22), <anonymous>:216:1)
	at HSnippet.eval [as generator] (eval at parse (c:\Users\Win33\Documents\Programming\hsnips\out\parser.js:115:22), <anonymous>:223:1)
	at new HSnippetInstance (c:\Users\Win33\Documents\Programming\hsnips\out\hsnippetInstance.js:39:36)
	at expandSnippet (c:\Users\Win33\Documents\Programming\hsnips\out\extension.js:61:27)
	at c:\Users\Win33\Documents\Programming\hsnips\out\extension.js:110:9
	at c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:977:271
	at Object.edit (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:242)
	at c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:977:260
	at _executeContributedCommand (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:675:513)
	at _doExecuteCommand (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:689)
	at _.executeCommand (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:595)
	at b._executeConvertedCommand (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:677:381)
	at _executeContributedCommand (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:675:513)
	at _.$executeContributedCommand (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:675:888)
	at g._doInvokeHandler (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:464)
	at g._invokeHandler (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:156)
	at g._receiveRequest (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:858:817)
	at g._receiveOneMessage (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:857:623)
	at c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:855:691
	at l.fire (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at v.fire (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1047:649
	at l.fire (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at v.fire (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at Object._receiveMessage (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
	at c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
	at l.fire (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at p.acceptChunk (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
	at c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
	at Socket.t (c:\Users\Win33\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:54)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

Not sure why this really happens. Maybe VSCode doesn't like/allow dynamic imports?

**Comment by draivin** [comment]
This is actually a limitation of `eval`, you can read about it here:
https://2ality.com/2019/10/eval-via-import.html

In any case, for such a thing to work, the module would have to be installed as an `hsnips` dependency, and as soon as we install a module as a dependency, we may as well pass it to the snippets code as a variable.

**Comment by itswin** [comment]
Hmm. You're right that `eval` doesn't support static imports, but dynamic imports seem to work fine if the module is installed globally. However, I'm just now realizing that even if these dynamic imports worked inside code interpolation, I would still have a problem of scoping and not being able to access the `rv` and `m` variables. Seeing this, getting any sort of imports to work would require a significant rewrite, like passing modules as variables through snippets as you said.

That's a shame, I was really hoping to get this to work. I guess I'll have to settle for my own parser if I want to evaluate some simple math expressions.

**Comment by draivin** [comment]
A possible solution is forwarding the `global` variable to the snippets, and in this way you would be able to `import` something the old way, such as `global.require('mathjs')`.

**Comment by draivin** [comment]
So, I did look into this a bit, and it seems like we are able to pass the `global` context of the executor to the snippet code, from which we can call `global.require`. There is an issue however, that globally installed modules are not available through imports, in fact, the only difference between globally installed modules is that they are available in the command line.

I'm a little bit rusty on JS, so I had forgotten how imports worked, but in any case, what this means is that only modules that are installed as dependencies for `hsnips` will be available for dynamic importing inside snippets, and as soon as this is the case, like I said before, we may as well pass then as variables instead of dynamic importing.

**Comment by draivin** [comment]
Following up on the edit in my last comment, the following does work, where I passed a slightly modified `requireGlobal` as the `global` variable:
```js
snippet import "import test"
``
let a = global('mathjs');
rv = a.evaluate("sqrt(3^2+4^2)");
``
endsnippet
```

**Comment by itswin** [comment]
Interesting! Would you mind creating a branch so I could see what you did?

**Comment by draivin** [comment]
Sorry for the delay in getting back to you, it's been a really busy week. [Here it is](https://github.com/draivin/hsnips/commit/084623b738ee0267a7bf57ef5eaa92117e20a797), just a rough sketch, in particular if we were to implement it, it would be good to also cache the `npm` call result, since depending on the machine it may take a while to run.
